/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchChannelIdRouteImport } from './routes/watch.$channelId'
import { Route as SettingsChannelsRouteImport } from './routes/settings.channels'
import { Route as WatchTvKeyRouteImport } from './routes/watch.tv.$key'
import { Route as WatchLiveSlugRouteImport } from './routes/watch.live.$slug'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'
import { Route as ApiPublicProbeRouteImport } from './routes/api/public/probe'
import { Route as ApiPublicMasterRouteImport } from './routes/api/public/master'
import { Route as ApiPublicAuratvMasterRouteImport } from './routes/api/public/auratv-master'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchChannelIdRoute = WatchChannelIdRouteImport.update({
  id: '/watch/$channelId',
  path: '/watch/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChannelsRoute = SettingsChannelsRouteImport.update({
  id: '/settings/channels',
  path: '/settings/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTvKeyRoute = WatchTvKeyRouteImport.update({
  id: '/watch/tv/$key',
  path: '/watch/tv/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLiveSlugRoute = WatchLiveSlugRouteImport.update({
  id: '/watch/live/$slug',
  path: '/watch/live/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProbeRoute = ApiPublicProbeRouteImport.update({
  id: '/api/public/probe',
  path: '/api/public/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMasterRoute = ApiPublicMasterRouteImport.update({
  id: '/api/public/master',
  path: '/api/public/master',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuratvMasterRoute = ApiPublicAuratvMasterRouteImport.update({
  id: '/api/public/auratv-master',
  path: '/api/public/auratv-master',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/status': typeof StatusRoute
  '/download': typeof DownloadRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
  '/api/public/auratv-master': typeof ApiPublicAuratvMasterRoute
  '/api/public/master': typeof ApiPublicMasterRoute
  '/api/public/probe': typeof ApiPublicProbeRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/watch/live/$slug': typeof WatchLiveSlugRoute
  '/watch/tv/$key': typeof WatchTvKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/status': typeof StatusRoute
  '/download': typeof DownloadRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
  '/api/public/auratv-master': typeof ApiPublicAuratvMasterRoute
  '/api/public/master': typeof ApiPublicMasterRoute
  '/api/public/probe': typeof ApiPublicProbeRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/watch/live/$slug': typeof WatchLiveSlugRoute
  '/watch/tv/$key': typeof WatchTvKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/status': typeof StatusRoute
  '/download': typeof DownloadRoute
  '/settings/channels': typeof SettingsChannelsRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
  '/api/public/auratv-master': typeof ApiPublicAuratvMasterRoute
  '/api/public/master': typeof ApiPublicMasterRoute
  '/api/public/probe': typeof ApiPublicProbeRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/watch/live/$slug': typeof WatchLiveSlugRoute
  '/watch/tv/$key': typeof WatchTvKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/status'
    | '/download'
    | '/settings/channels'
    | '/watch/$channelId'
    | '/api/public/auratv-master'
    | '/api/public/master'
    | '/api/public/probe'
    | '/api/public/stream'
    | '/watch/live/$slug'
    | '/watch/tv/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/status'
    | '/download'
    | '/settings/channels'
    | '/watch/$channelId'
    | '/api/public/auratv-master'
    | '/api/public/master'
    | '/api/public/probe'
    | '/api/public/stream'
    | '/watch/live/$slug'
    | '/watch/tv/$key'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/status'
    | '/download'
    | '/settings/channels'
    | '/watch/$channelId'
    | '/api/public/auratv-master'
    | '/api/public/master'
    | '/api/public/probe'
    | '/api/public/stream'
    | '/watch/live/$slug'
    | '/watch/tv/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  StatusRoute: typeof StatusRoute
  DownloadRoute: typeof DownloadRoute
  SettingsChannelsRoute: typeof SettingsChannelsRoute
  WatchChannelIdRoute: typeof WatchChannelIdRoute
  ApiPublicAuratvMasterRoute: typeof ApiPublicAuratvMasterRoute
  ApiPublicMasterRoute: typeof ApiPublicMasterRoute
  ApiPublicProbeRoute: typeof ApiPublicProbeRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
  WatchLiveSlugRoute: typeof WatchLiveSlugRoute
  WatchTvKeyRoute: typeof WatchTvKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$channelId': {
      id: '/watch/$channelId'
      path: '/watch/$channelId'
      fullPath: '/watch/$channelId'
      preLoaderRoute: typeof WatchChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/channels': {
      id: '/settings/channels'
      path: '/settings/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof SettingsChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/tv/$key': {
      id: '/watch/tv/$key'
      path: '/watch/tv/$key'
      fullPath: '/watch/tv/$key'
      preLoaderRoute: typeof WatchTvKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/live/$slug': {
      id: '/watch/live/$slug'
      path: '/watch/live/$slug'
      fullPath: '/watch/live/$slug'
      preLoaderRoute: typeof WatchLiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/probe': {
      id: '/api/public/probe'
      path: '/api/public/probe'
      fullPath: '/api/public/probe'
      preLoaderRoute: typeof ApiPublicProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/master': {
      id: '/api/public/master'
      path: '/api/public/master'
      fullPath: '/api/public/master'
      preLoaderRoute: typeof ApiPublicMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auratv-master': {
      id: '/api/public/auratv-master'
      path: '/api/public/auratv-master'
      fullPath: '/api/public/auratv-master'
      preLoaderRoute: typeof ApiPublicAuratvMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  StatusRoute: StatusRoute,
  DownloadRoute: DownloadRoute,
  SettingsChannelsRoute: SettingsChannelsRoute,
  WatchChannelIdRoute: WatchChannelIdRoute,
  ApiPublicAuratvMasterRoute: ApiPublicAuratvMasterRoute,
  ApiPublicMasterRoute: ApiPublicMasterRoute,
  ApiPublicProbeRoute: ApiPublicProbeRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
  WatchLiveSlugRoute: WatchLiveSlugRoute,
  WatchTvKeyRoute: WatchTvKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
